version: '3.1'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
    ports:
      - '4566-4583:4566-4583'
